### ISSUE TITLE
APK available?

### ISSUE THREAD

**Issue by IzzySoft** [1fish2/BBQTimer#4]
Did you consider making the APK available to those outside of PlayStore? Some folks cannot (or do not want to) use Google accounts/connections on their device(s). Providing a (signed) APK attached to the Release tags would open the app to them, too (and I then even could make it available via [my repo](https://apt.izzysoft.de/fdroid) for easier discovery, installation and updates). Thanks in advance!

**Comment by 1fish2** [comment]
OK. I attached the signed APK to the release 3.0 tag and added a note to my release procedures to do that in the future. Enjoy!

**Comment by IzzySoft** [comment]
Thanks a lot! Your app will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.onefishtwo.bbqtimer) with the next sync around 6 pm UTC tomorrow. Be welcome to use [a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link to this place from your Readme :smiley:

As you might ask: yes, updates will be fetched automatically within 24h of your tagging a new release and attaching an APK to it. And users can use the [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) of their choice to keep the app updated (they just need to add my repo to it if it's not already there; some clients have it in by default, others not).

Should you wish to apply for inclusion with F-Droid's own repo (your app seems to meet all criteria, as far as I can see), I gladly help you with that (disclosure: I'm one of the maintainers there). As a first step, I could provide you a "starter package" to establish [Fastlane structures](https://gitlab.com/-/snippets/1895688) here in your app's repo, so you're in full control of the presentation and screenshots can be included with the listing. Note that the very same fastlane structure can be used for deployment to Play, if you add the Fastlane binaries on top (not needed for F-Droid, but for deployment to Play).

**Comment by 1fish2** [comment]
Please do send the info on F-Droid with the starter package for Fastlane. It's not something I've looked into. Thanks!

Do your repo and F-Droid notice new APK releases automatically or is there a manual trigger? Is there a signal to clearly distinguish full releases from alpha- and beta-test releases?

**Comment by IzzySoft** [comment]
Starter package available at #5 and waiting to be merged :smiley: And yes, both of us (F-Droid and my repo) are able to check for updates automatically. The signal to pick something up is a new tag being created (with an APK for my repo). You can have my repo distinguish that by using pre-release tags for everything I should skip; the clean way would be using "tag prefixes" – e.g. `beta-1.2.3` (or `pre-1.2.3`) for a beta release, and `release-1.2.5` for a stable release. Using `pre-` and `release-` would enable you later to have F-Droid only serve the stable ones (`release-*`) while keeping versions for your testers (`pre-*`) available via mine, if you want such a thing.
