### ISSUE TITLE
Fastlane: German full_description.txt too long

### ISSUE THREAD

**Issue by IzzySoft** [1fish2/BBQTimer#9]
The limit for `full_description.txt` is 4.000 chars – the file currently has 4.133 chars and hence will be truncated. Could you please see what might be removed, so it doesn't end mid-sentence?

**Comment by IzzySoft** [comment]
My scanner just reminded me of this, so I took a closer look: the resulting HTML is at 4081 chars, which leads to the truncation. Is there a chance to reduce it by ~81 chars? For example, the nested bullet point in line 2 could be integrated into the first bullet point would save about 15 chars:

```markdown
* <b>Kombinierter Intervalltimer/Stoppuhr</b> = periodische Alarme + verstrichene Zeit.  
Erinnert Sie regelmäßig daran, die Speisen zu wenden und verfolgt die gesamte Garzeit.
```

(the 2 spaces at the end of line 1 will produce a `<br>`). Changing "Tippen Sie auf …" to "auf … tippen" would save another 20+ chars.

**Comment by 1fish2** [comment]
Yes. Checked in. You'd know about the fit and the German translation way better than me.

Let me know if you need anything else.

**Comment by IzzySoft** [comment]
Whenever my scanner detects something, I of course transport that "upstream" :wink: So thanks a lot for fixing – and I'm glad I was able to contribute!

(Btw: that scan only runs once per month, so I won't come with such messages too often :see_no_evil:)

**Comment by IzzySoft** [comment]
Grmpf. Formatted as HTML (which my updater does on import), the file has 4081 chars – which is 81 too much. Can it be shortened a bit? To shorten quite a bit: do the Tipps really need to be in the app description?

**Comment by 1fish2** [comment]
Oh. OK. I'll cut out some tips soon.

Is there a good, lightweight library to display one-time tips in app?

**Comment by IzzySoft** [comment]
> Is there a good, lightweight library to display one-time tips in app?

I don't know. Guess there is, you won't be the first one thinking about this. But all that comes to mind at the moment for me is onboarding activities…

**Comment by 1fish2** [comment]
I trimmed 837 chars from `fastlane/metadata/android/de/full_description.txt`. That should do it.

**Comment by IzzySoft** [comment]
Yes, that should definitely suffice. Thanks a lot!
